import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';

const displayFont = localFont({
  src: [
    {
      path: '../../../packages/ui/src/assets/fonts/Outfit.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-ultra-display', // 👈 Unique variable for headings
});

// 📦 Font 2: Body Font (e.g., Ultra Sans)
const bodyFont = localFont({
  src: [
    {
      path: '../../../packages/ui/src/assets/fonts/Outfit.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-ultra-body', // 👈 Unique variable for body copy
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${displayFont.variable} ${bodyFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
